[package]
edition = "2024"
name = "entry-call"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = {version = "2.0.113", features = ["full", "extra-traits", "visit-mut"]}
